//! How a patch reads itself, and what it does with a key it has no field
//! for: name it, and carry on.
//!
//! A config being ported is the case this exists for. One property coolabah has
//! no field for yet — or one typo — should not stop the other forty from
//! coming up, and it must not pass in silence either: a converter that reads
//! the keys it knows and drops the rest configures nothing and says nothing,
//! which is the failure this is here to stop.
//!
//! It belongs to the patch rather than to whoever is reading one, because the
//! answer is the same however the key arrived. `sketchybar --set clock wat=1`
//! and `item:set{ wat = 1 }` are the same mistake and now get the same
//! sentence, without either front end knowing anything about it.
//!
//! Nothing here buffers. [`Reader`] walks the live map and hands each value
//! straight to the field that claims it through [`Patch::absorb`], which is
//! what lets `padding_left=5` out of argv become an `f64` — the *field's*
//! type is what asks for it. `#[serde(flatten)]` cannot do that: it collects
//! every unclaimed key into `serde`'s own value tree first, and a buffered
//! `f64` field handed the string `5` fails.

use serde::de::{IgnoredAny, MapAccess, Visitor};
use serde::{Deserialize, Deserializer};
use std::fmt;
use std::marker::PhantomData;

/// What a patch knows about itself for the sake of a good error message.
///
/// Generated by `#[derive(Changes)]` from the declaration it patches, so a
/// new property is a key this already knows about. [`Self::GAPS`] is the one
/// part a macro cannot work out — a judgement about what `SketchyBar` has and
/// coolabah does not — and is declared as `#[changes(gap(...))]` beside the
/// type.
pub trait Fields {
    /// What a config calls this table, as it would read in a sentence —
    /// `an item`, `an item's icon or label`.
    const WHAT: &'static str;

    /// Every key this patch answers to itself, aliases included.
    const KEYS: &'static [&'static str];

    /// The keys of every patch flattened into this one — spelled as if they
    /// were this patch's own, because on the wire they are.
    ///
    /// Composed rather than re-listed: `ItemPatch` learns `padding_left` from
    /// `GeometryPatch`, so adding a property to `Geometry` needs no edit
    /// here.
    const NESTED: &'static [&'static [&'static str]] = &[];

    /// Real `SketchyBar` properties this patch has no field for yet, and why
    /// — `(key, note)`. Told apart from a typo because the two want opposite
    /// answers: fix the spelling, or wait for the feature.
    const GAPS: &'static [(&'static str, &'static str)] = &[];
}

/// Every key `T` accepts, its flattened sub-patches' included.
pub fn keys<T: Fields + ?Sized>() -> impl Iterator<Item = &'static str> + Clone {
    T::KEYS
        .iter()
        .copied()
        .chain(T::NESTED.iter().flat_map(|nested| nested.iter().copied()))
}

/// One key of a patch, read straight out of the map.
///
/// Generated by `#[derive(Changes)]`. The value is never buffered: whichever
/// field claims the key calls `next_value` itself, so its own type decides
/// how the text is read. A flattened sub-patch is offered the key after the
/// outer patch's own fields have declined it, which is what lets several of
/// them share one table without the first swallowing the rest.
pub trait Patch<'de>: Sized + Default {
    /// Reads `key`'s value into this patch if it names one of its
    /// properties, and says whether it did.
    ///
    /// # Errors
    ///
    /// Returns the map's own error if the value does not read as the field's
    /// type.
    fn absorb<A: MapAccess<'de>>(&mut self, key: &str, map: &mut A) -> Result<bool, A::Error>;
}

/// Two spellings of the same property, as one.
///
/// The blanket answer is "the later one wins", which is right for a leaf. A
/// generated patch has an *inherent* `folded` that folds field by field
/// instead, and an inherent method wins method resolution against this — so
/// `label=12:34 label.color=0xff00ff00` comes to one `RunPatch` carrying
/// both, rather than the colour alone.
pub trait Fold: Sized {
    /// What this and `other` come to together.
    #[must_use]
    fn folded(self, other: Self) -> Self {
        other
    }
}

impl<T> Fold for T {}

/// A patch's own `Visitor`: one pass over the live map, every value read by
/// the field it belongs to, every key nothing claimed reported and dropped.
pub struct Reader<T: ?Sized>(PhantomData<fn() -> T>);

impl<T: ?Sized> Reader<T> {
    #[must_use]
    pub const fn new() -> Self {
        Self(PhantomData)
    }
}

impl<T: ?Sized> Default for Reader<T> {
    fn default() -> Self {
        Self::new()
    }
}

impl<'de, T: Fields + Patch<'de>> Visitor<'de> for Reader<T> {
    type Value = T;

    fn expecting(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "the properties of {}", T::WHAT)
    }

    fn visit_map<A: MapAccess<'de>>(self, mut map: A) -> Result<T, A::Error> {
        let mut patch = T::default();
        while let Some(key) = map.next_key::<String>()? {
            if !patch.absorb(&key, &mut map)? {
                map.next_value::<IgnoredAny>()?;
                report::<T>(&key);
            }
        }
        Ok(patch)
    }
}

/// Every required property a patch did not name.
///
/// Typed rather than a formatted string so both front ends can render it
/// themselves: the CLI prints it, the Lua host raises it with a traceback,
/// and neither has to re-parse a sentence the other wrote. Names all of them
/// at once — a config author fixing one omission at a time is a bad
/// afternoon, and the information was all there the first time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Missing {
    /// What was being built, as [`Fields::WHAT`] spells it.
    pub what: &'static str,
    /// Every required property that was absent, in declaration order.
    pub fields: Vec<&'static str>,
}

impl Missing {
    /// `None` when nothing is missing, which is the ordinary case and not an
    /// error at all.
    #[must_use]
    pub fn new(what: &'static str, fields: Vec<&'static str>) -> Option<Self> {
        (!fields.is_empty()).then_some(Self { what, fields })
    }
}

impl fmt::Display for Missing {
    /// The same shape a bad *value* gets — `` `label.color`: `puce` is not a
    /// colour `` — so a config author reads one dialect, not two.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let named = self
            .fields
            .iter()
            .map(|field| format!("`{field}`"))
            .collect::<Vec<_>>()
            .join(", ");
        write!(f, "{named}: required to build {}, and not set", self.what)
    }
}

impl std::error::Error for Missing {}

/// `alias = { color = ... }`, which is how `SketchyBar`'s own Lua helper
/// tints the menu bar icon an alias mirrors.
///
/// coolabah's `alias` carries the target's name and nothing else, so the table is
/// named and dropped rather than refused: one missing tint is not a reason to
/// fail the whole `add`, and a real config does write this. The `untagged`
/// enum is only asked which shape arrived — a name, or the table — because
/// that is the one question a generic "did not match any variant" answers
/// well.
///
/// # Errors
///
/// Returns an error only for a value that is neither a string nor a table.
pub fn name_or_tinted<'de, D: Deserializer<'de>>(
    deserializer: D,
) -> Result<Option<String>, D::Error> {
    #[derive(Deserialize)]
    #[serde(untagged)]
    // A map whose values are zero-sized, which clippy suggests replacing with
    // a set. A set deserializes from a *list*; this has to deserialize from
    // the table a config wrote, and the values are exactly what is being
    // dropped -- only the keys are worth naming.
    #[allow(clippy::zero_sized_map_values)]
    enum AliasRepr {
        Name(String),
        Tinted(std::collections::BTreeMap<String, IgnoredAny>),
    }

    Ok(match Option::<AliasRepr>::deserialize(deserializer)? {
        Some(AliasRepr::Name(name)) => Some(name),
        Some(AliasRepr::Tinted(properties)) => {
            let dropped = properties.keys().cloned().collect::<Vec<_>>().join(", ");
            tracing::error!(
                what = "an item",
                key = "alias",
                "recognised, but not implemented: tinting the mirrored menu bar icon \
                 (dropped: {dropped}); coolabah's `alias` carries only the target's name"
            );
            None
        }
        None => None,
    })
}

/// Says the most useful true thing about `key`, in this order: a property
/// `SketchyBar` really has and coolabah does not; a real property written one
/// level too deep, which is the likelier mistake and the more annoying one to
/// find; a near miss worth suggesting; and otherwise that it does nothing.
fn report<T: Fields + ?Sized>(key: &str) {
    if let Some((_, note)) = T::GAPS.iter().find(|(gap, _)| *gap == key) {
        tracing::error!(
            what = T::WHAT,
            key,
            "recognised, but not implemented: {note}"
        );
    } else if keys::<crate::ItemPatch>().any(|field| field == key) {
        tracing::error!(
            what = T::WHAT,
            key,
            "unknown setting here; `{key}` belongs to the item itself, not to {}",
            T::WHAT
        );
    } else if let Some(guess) = nearest(key, keys::<T>()) {
        tracing::error!(
            what = T::WHAT,
            key,
            "unknown setting; did you mean `{guess}`?"
        );
    } else {
        tracing::error!(what = T::WHAT, key, "unknown setting; it does nothing");
    }
}

/// The known key closest to `key`, when one is close enough to be worth
/// suggesting — a prefix, a suffix, or a one-character slip.
fn nearest<'a>(key: &str, known: impl Iterator<Item = &'a str> + Clone) -> Option<&'a str> {
    known
        .clone()
        .find(|candidate| {
            candidate.starts_with(key)
                || candidate.ends_with(key)
                || key.starts_with(*candidate)
                || key.ends_with(candidate)
        })
        .or_else(|| {
            known.into_iter().find(|candidate| {
                candidate.len().abs_diff(key.len()) <= 1
                    && candidate
                        .chars()
                        .zip(key.chars())
                        .filter(|(a, b)| a != b)
                        .count()
                        <= 1
            })
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Thing;

    impl Fields for Thing {
        const WHAT: &'static str = "a thing";
        const KEYS: &'static [&'static str] = &["color", "corner_radius"];
        const GAPS: &'static [(&'static str, &'static str)] = &[("clip", "nothing clips yet")];
    }

    #[test]
    fn a_near_miss_is_worth_suggesting_and_a_wild_one_is_not() {
        assert_eq!(nearest("colour", keys::<Thing>()), Some("color"));
        assert_eq!(nearest("corner", keys::<Thing>()), Some("corner_radius"));
        assert_eq!(nearest("wat", keys::<Thing>()), None);
    }

    #[test]
    fn nothing_missing_is_not_an_error() {
        assert_eq!(Missing::new("an item", Vec::new()), None);
        assert_eq!(
            Missing::new("an item", vec!["position"])
                .expect("one is missing")
                .to_string(),
            "`position`: required to build an item, and not set"
        );
    }
}
