[package]
name = "rsbar"
description = "A configurable status bar for macOS."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "rsbar"
path = "src/lib.rs"

[[bin]]
name = "rsbard"
path = "src/main.rs"

[dependencies]
async-mach-ports = { workspace = true }
rsbar-protocol = { workspace = true }
skylight = { workspace = true }
objc2-core-foundation = { workspace = true, features = ["CFArray", "CFAttributedString", "CFDictionary", "CFNumber", "CFString", "CFCGTypes", "CFRunLoop"] }
objc2-core-graphics = { workspace = true, features = ["CGContext", "CGColor", "CGColorSpace", "CGDirectDisplay", "CGDisplayConfiguration", "CGError", "CGEvent", "CGEventTypes", "CGPath"] }
objc2-core-text = { workspace = true, features = ["CTFont", "CTFontDescriptor", "CTLine", "CTStringAttributes", "objc2-core-graphics"] }
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_time = { workspace = true }
block2 = "0.6"
futures-lite = { workspace = true }
notify = { workspace = true }
objc2 = { workspace = true }
objc2-app-kit = { workspace = true, features = ["NSWorkspace", "NSRunningApplication", "NSApplication", "NSResponder", "NSScreen", "NSEvent", "NSGraphics", "objc2-core-foundation"] }
objc2-foundation = { workspace = true, features = ["NSNotification", "NSString", "NSDictionary", "NSOperation", "NSValue", "NSObject", "NSArray", "NSDate", "NSRunLoop", "block2"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
