[package]
name = "skylight"
description = "Bindings to the private SkyLight/CoreGraphics-Services window server APIs."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
bitflags = { workspace = true }
objc2-core-foundation = { workspace = true, features = ["CFArray", "CFNumber", "CFString", "CFCGTypes"] }
objc2-core-graphics = { workspace = true, features = ["CGError", "CGDirectDisplay", "CGContext", "CGImage", "CGWindow"] }
objc2-quartz-core = { workspace = true, features = ["CALayer", "CATransaction", "objc2-core-foundation", "objc2-core-graphics"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
objc2-core-foundation = { workspace = true, features = ["CFRunLoop"] }
objc2-core-graphics = { workspace = true, features = ["CGEvent", "CGEventTypes", "CGEventSource"] }
