-- Ports sketchybar/items/secondary.lua: a minimal second bar (just the
-- workspaces widget plus a window-title item) on a specific physical
-- display's arrangement ID.
--
-- TODO(coolabah): neither `Request::AddItem` nor `ItemPatch`
-- (crates/protocol/src/lib.rs) take a `display` -- there is no way to pin an
-- item to one physical display. `BarState.displays` only reports *how many*
-- there are, not which is which, and there is no per-display bar
-- configuration at all. Duplicating `front_app`'s content into a second,
-- identically-named-but-different item would not land on "just display 2"
-- the way the original does -- it would just draw a second, redundant title
-- item on whichever bar coolabah actually renders. Rather than ship something
-- that looks like it works but silently means something else, this item is
-- left out of the port entirely.
return function() end
