[package]
name = "rsbar-protocol"
description = "Wire types shared by the rsbar daemon, CLI and Lua module."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
struct-patch = "0.14.1"
thiserror = { workspace = true }

[dev-dependencies]
postcard = { version = "1.1", features = ["use-std"] }

[lints]
workspace = true
