[package]
name = "rsbar-cli"
description = "Command line client for the rsbar daemon."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rsbar"
path = "src/main.rs"

[dependencies]
async-mach-ports = { workspace = true }
clap = { version = "4.6", features = ["derive"] }
rsbar-protocol = { workspace = true }

[lints]
workspace = true
